### ISSUE TITLE
Use Roslynator for docs?

### ISSUE THREAD

**Issue by benjamin-hodgson** [benjamin-hodgson/BuildScripts#10]
[Roslynator](https://josefpihrt.github.io/docs/roslynator/) can cook xmldocs into markdown pages, seems faster and better supported than docfx. Then the markdown can be displayed with whatever static site generator you like. There's built in support for [Docusaurus](https://docusaurus.io)-flavoured-markdown and [Sphinx](https://www.sphinx-doc.org), but can also use [starlight](https://starlight.astro.build) or [Hakyll](https://jaspervdj.be/hakyll/) or [MkDocs](https://www.mkdocs.org/) or whatever other markdown renderer.

```bash
roslynator generate-doc Gutenberg/Gutenberg.csproj -o my-website/docs --heading Gutenberg --host docusaurus --group-by-common-namespace
```

Would need to figure out C# syntax highlighting.

**Comment by benjamin-hodgson** [comment]
mkdocs

```yaml
site_name: Gutenberg

site_url: https://benjamin.pizza/Gutenberg

theme:
    name: material
    features:
        - navigation.indexes
```
